import os.path
from SConfig import *
Import('environment')

testSources = ['main.cpp','gmock-gtest-all.cc']

environment.Append(CCFLAGS = [ '-g', '-O0'])
libPath = '#' + os.path.join(BUILD_DIR, DEBUG_CONFIG)
test = environment.Program(target = TEST_TARGET, source = testSources, LIBS = ['pthread', LIB_TARGET], 
LIBPATH = libPath, CPPPATH = ['#src', '#include', '.'])
testInstallPath = '#' + os.path.join(OUTPUT_DIR, TEST_CONFIG)
environment.Install(testInstallPath, test)

testRunPath = os.path.join(OUTPUT_DIR, TEST_CONFIG, TEST_TARGET)
if environment['PLATFORM'] != 'posix':
	testRunPath += '.exe'
	
testRun = environment.Command(target = 'testRun', source = testSources, action = testRunPath)
Depends( testRun, test )
AlwaysBuild(testRun)
