from SConfig import *

Import('environment')
testSources = ['main.cpp']
test = environment.Program(target = TEST_TARGET, source = testSources, LIBS = [], LIBPATH = '#' + BUILD_DIR + '/' + RELEASE_CONFIG)
environment.Install('#' + OUTPUT_DIR + '/' + TEST_CONFIG, test)

if environment['PLATFORM'] == 'posix':
	testRun = Command(target = 'testRun', source = testSources, action = OUTPUT_DIR + '/' + TEST_CONFIG +'/' + TEST_TARGET)
else:
	testRun = Command(target = 'testRun', source = testSources, action = OUTPUT_DIR + '\\' + TEST_CONFIG +'\\' + TEST_TARGET + '.exe')

AlwaysBuild(testRun)
