from SConfig import *

Import('environment')
testSources = ['main.cpp']
testMain = environment.Program(testSources, LIBS = [], LIBPATH = '#' + BUILD_DIR + '/' + RELEASE_CONFIG)
environment.Install('#' + OUTPUT_DIR + '/' + TEST_CONFIG, testMain)

if environment['PLATFORM'] == 'posix':
	test = Command(target = 'test', source = testSources, action = OUTPUT_DIR + '/' + TEST_CONFIG +'/' + 'testMain')
else:
	test = Command(target = 'test', source = testSources, action = OUTPUT_DIR + '\\' + TEST_CONFIG +'\\' + 'testMain.exe')

AlwaysBuild(test)
