import os.path
from SConfig import *

libSources = Glob('*.cpp')
libSources.extend(Glob('crypto/*.cpp'))

Import('configuration')
Import('environment')
Import('buildWithRsa')
Import('opensslLibPath')
        
def compileDebug():
    environment.Append( CCFLAGS = [ '-g', '-O0'] )
    commonBuild()

def compileRelease():
    environment.Append( CCFLAGS = ['-O2'] )
    commonBuild()

def compileTest():
    commonBuild()

def commonBuild():
    oauthLib = environment.StaticLibrary(LIB_TARGET, libSources)
    installDirPath = '#' + os.path.join(OUTPUT_DIR, configuration)
    environment.Install(installDirPath, oauthLib)

libSources.extend([f for f in Glob('utility/*.cpp')
    if os.path.join('utility', 'RsaSignature.cpp') not in f.path])
if buildWithRsa:
    libSources.extend(Glob('crypto/rsa/*.cpp'))
    libSources.extend(environment.Object(os.path.join('utility', 'RsaSignature.cpp'), CCFLAGS='-fpermissive'))
else:
    # Do not build RsaSignature.cpp
    print 'Building library without RSA-SHA1 signature method'
    libSources.extend([f for f in Glob('utility/*.cpp')
        if os.path.join('utility', 'RsaSignature.cpp') not in f.path])

if configuration == DEBUG_CONFIG:
    compileDebug()
elif configuration == RELEASE_CONFIG:
    compileRelease()
else:
    print 'Unknown configuration'
